### ISSUE TITLE
Disable /reload

### ISSUE THREAD

**Issue by drtshock** [Minehut/Issues#119]
We need to disable /reload which causes issues with plugins that we wouldn't see if we disabled this.

**Comment by tjhubz** [comment]
Instead, make users type the command again, and declare that any issues with the server after reloading are not at the fault of Minehut, and may require a reset of the entire server.

The reason for this is because reloading can be really useful to some players, and doesn't always cause issues. Essentially everyone has used the /reload command multiple times already.

**Comment by MatrixTunnel** [comment]
Maybe we could implement something similar to how Paper's reload command works (`/reload confirm`)

**Comment by drtshock** [comment]
I disabled it. We're going to make you restart. There's no good reason to allow reload that makes it worth the risk and invalid bug reports.

Will be pushed in next release.
